name: Move to review card
on:
  pull_request:
    types:  [opened,reopened,review_requested,ready_for_review]
jobs:
  move-review-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Feature Tracking
          column: To Review
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}