name: Move to review card
on:
  pull_request:
    types:  [opened,reopened,review_requested,ready_for_review]
jobs:
  move-review-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Feature Tracking
          column: To Review
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}